"""
Wires up Marcy's test scoring. Do not edit this file.

It makes `score_tests.py` importable from the repo root, installs the
pre-commit hook, and registers the plugin that writes `scores/scores.json`
after every test run.
"""

import shutil
import stat
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "src"))

import score_tests  # noqa: E402  (must follow the sys.path setup above)


def _install_git_hook():
    """Copy hooks/pre-commit into .git/hooks.

    The JavaScript version did this through npm's `preinstall` script. `pip
    install` has no equivalent, and without it scores/scores.json never
    updates on commit, so we do it here on the first test run instead.

    Silent and best-effort: a missing .git (zip download, no git) is fine,
    and a read-only checkout must never break the test suite.
    """
    source = REPO_ROOT / "hooks" / "pre-commit"
    hooks_dir = REPO_ROOT / ".git" / "hooks"
    if not source.is_file() or not hooks_dir.is_dir():
        return
    target = hooks_dir / "pre-commit"
    try:
        if target.is_file() and target.read_bytes() == source.read_bytes():
            return
        shutil.copyfile(source, target)
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
    except OSError:
        pass


def pytest_configure(config):
    _install_git_hook()
    score_tests.register(config, REPO_ROOT)
